### ISSUE TITLE
[Feature] Click on station in result table to view its data

### ISSUE THREAD

**Issue by Thibstars** [Thibstars/belgian-train-station-chrome#1]
**Is your feature request related to a problem? Please describe.**
It would be easy to quickly view the data of a station displayed in the currently shown station.

**Describe the solution you'd like**
When I have looked up a station, I can see its departures. Now I'd like to see the departures of one of the stations that are included in the currently shown table. My proposal is to be able to simply click on a station in the table in order to show the data of the clicked station.

**Describe alternatives you've considered**
The alternative is to manually type in the station that you want to look up.

**Comment by MananPoojara** [comment]
For the station let say Statta, what you can do is provide only the available stations. When the user clicks on a station, the table for that particular station is displayed. another thing you can do also, when you click on let's say Namur, a designed paragraph appears below the button.

**Comment by Thibstars** [comment]
> For the station let say Statta, what you can do is provide only the available stations. When the user clicks on a station, the table for that particular station is displayed. another thing you can do also, when you click on let's say Namur, a designed paragraph appears below the button.

Thanks for the suggestions. I might consider some kind of auto-complete in the future, though this issue just addressed the possibility to click through stations in the table :)
